require: rubocop-rspec

inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'config/environments/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/waiver_infos_controller.rb'
    - 'app/mailers/waiver_mailer.rb'
    - 'app/models/employee.rb'
    - 'lib/author_status.rb'
    - 'lib/tasks/import_waivers.rake'

Metrics/BlockLength:
  Exclude:
    - 'app/models/employee.rb'
    - 'config/routes.rb'
    - 'lib/tasks/import_authors.rake'
    - 'lib/tasks/import_waivers.rake'
    - 'lib/tasks/report.rake'
    - 'spec/controllers/accounts_controller_spec.rb'
    - 'spec/controllers/application_controller_spec.rb'
    - 'spec/controllers/employees_controller_spec.rb'
    - 'spec/controllers/waiver_infos_controller_spec.rb'
    - 'spec/models/employee_spec.rb'
    - 'spec/models/waiver_info_spec.rb'
    - 'spec/requests/accounts_spec.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/waiver_infos_controller.rb'
    - 'app/models/employee.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/mailers/waiver_mailer.rb'
    - 'app/models/employee.rb'
    - 'app/models/waiver_info.rb'
    - 'lib/author_status.rb'
    - 'lib/tasks/import_waivers.rake'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/waiver_infos_controller.rb'
    - 'app/mailers/waiver_mailer.rb'
    - 'app/models/employee.rb'
    - 'lib/author_status.rb'
    - 'lib/tasks/import_waivers.rake'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/tasks/import_waivers.rake'
    - 'app/mailers/waiver_mailer.rb'
    - 'app/models/employee.rb'
    - 'lib/author_status.rb'

