default: &default
  adapter: mysql2
  encoding: utf8mb4
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 40)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

development: &development
  <<: *default
  database: <%= ENV["lando_oawaiver_database_creds_database"] || "oawaiver_development" %>
  host: <%= ENV["lando_oawaiver_database_conn_host"] || "localhost" %>
  port: <%= ENV["lando_oawaiver_database_conn_port"] || 3306 %>
  username: <%= ENV["lando_oawaiver_database_creds_user"] %>
  password: <%= ENV["lando_oawaiver_database_creds_password"] %>

test:
  <<: *development
  database: <%= ENV["lando_oawaiver_database_creds_database"] || "oawaiver_test" %>
  host: <%= ENV["lando_oawaiver_database_conn_host"] || ENV.fetch("APP_DB_HOST", 'localhost') %>
  port: <%= ENV["lando_oawaiver_database_conn_port"] || ENV.fetch("APP_DB_PORT", 3306) %>
  username: <%= ENV["lando_oawaiver_database_creds_user"] || ENV.fetch("APP_DB_USERNAME", 'oawaiver') %>
  password: <%= ENV["lando_oawaiver_database_creds_password"] || ENV.fetch("APP_DB_PASSWORD", 'oawaiver') %>

staging: &staging
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV["APP_DB"] %>
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
  host: <%= ENV["APP_DB_HOST"] %>
  port: <%= ENV["APP_DB_PORT"] || 3306 %>
  username: <%= ENV["APP_DB_USERNAME"] %>
  password: <%= ENV["APP_DB_PASSWORD"] %>

production:
  <<: *staging
