
default: &default
  solr:
    hostname: <%= ENV["lando_oawaiver_solr_conn_host"] || ENV["APP_SOLR_HOST"] || "localhost" %>
    port: 8983

development:
  <<: *default
  solr:
    hostname: <%= ENV["lando_oawaiver_solr_conn_host"] || ENV["APP_SOLR_HOST"] || "localhost" %>
    port: 8983
    log_level: DEBUG
    path: /solr/oawaiver-development

test:
  <<: *default
  solr:
    hostname: <%= ENV["lando_oawaiver_solr_conn_host"] || ENV["APP_SOLR_HOST"] || "localhost" %>
    port: 8983
    log_level: DEBUG
    path: /solr/oawaiver-test

staging: &staging
  <<: *default
  solr:
    hostname: <%= ENV["APP_SOLR_HOST"] || "localhost" %>
    port: 8080
    log_level: INFO
    path: /solr/oawaiver-production

production:
  <<: *staging
