
default: &default
  solr:
    hostname: <%= ENV["APP_SOLR_HOST"] || "localhost" %>
    port: <%= ENV["APP_SOLR_PORT"] || 8983 %>

development:
  <<: *default
  solr:
    hostname: <%= ENV["lando_oawaiver_development_solr_conn_host"] || ENV["APP_SOLR_HOST"] || "localhost" %>
    port: <%= ENV["lando_oawaiver_development_solr_conn_port"] || ENV["APP_SOLR_PORT"] || 8983 %>
    log_level: DEBUG
    path: <%= ENV["APP_SOLR_PATH"] || "/solr/oawaiver-core-dev" %>

test:
  <<: *default
  solr:
    hostname: <%= ENV["lando_oawaiver_test_solr_conn_host"] || ENV["APP_SOLR_HOST"] || "localhost" %>
    port: <%= ENV["lando_oawaiver_test_solr_conn_port"] || ENV["APP_SOLR_PORT"] || 8983 %>
    log_level: DEBUG
    path: <%= ENV["APP_SOLR_PATH"] || "/solr/oawaiver-core-test" %>

staging: &staging
  <<: *default
  solr:
    log_level: INFO
    path: <%= ENV["APP_SOLR_PATH"] || "/solr/oawaiver-staging" %>

production:
  <<: *staging
  solr:
    path: <%= ENV["APP_SOLR_PATH"] || "/solr/oawaiver-production" %>
