
default:
  solr: &default
    hostname: <%= ENV["APP_SOLR_HOST"] || "localhost" %>
    port: <%= ENV["APP_SOLR_PORT"] || 8983 %>

development:
  solr: &development
    <<: *default
    hostname: <%= ENV["lando_oawaiver_development_solr_conn_host"] || ENV["APP_SOLR_HOST"] || "localhost" %>
    port: <%= ENV["lando_oawaiver_development_solr_conn_port"] || ENV["APP_SOLR_PORT"] || 8983 %>
    log_level: DEBUG
    path: <%= ENV["APP_SOLR_PATH"] || "/solr/oawaiver-core-dev" %>

test:
  solr:
    <<: *development
    hostname: <%= ENV["lando_oawaiver_test_solr_conn_host"] || ENV["APP_SOLR_HOST"] || "localhost" %>
    port: <%= ENV["lando_oawaiver_test_solr_conn_port"] || ENV["APP_SOLR_PORT"] || 8983 %>
    path: <%= ENV["APP_SOLR_PATH"] || "/solr/oawaiver-core-test" %>

staging:
  solr: &staging
    <<: *default
    log_level: INFO
    path: <%= ENV["APP_SOLR_PATH"] || "/solr/oawaiver-staging" %>

production:
  solr:
    <<: *staging
    path: <%= ENV["APP_SOLR_PATH"] || "/solr/oawaiver-production" %>
